sudo: required

services: docker

language: python

python: "3.4"

install: docker pull cs50/cli

script: docker run -v${TRAVIS_BUILD_DIR}:/root/python-cs50/ --rm cs50/cli cd python-cs50; make install; python test/sqltests.py
