language: python

python: "3.4"

services:
  - mysql
  - postgres

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cs50_sql_tests;'
  - psql -c 'create database cs50_sql_tests;' -U postgres
  - pip install mysqlclient psycopg2

install:
  - python setup.py sdist
  - pip install dist/*.tar.gz

script: python test/sqltests.py
