language: python

python: "3.4"

services:
  - mysql
  - postgres

before_install:
  - make build
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cs50_sql_tests;'
  - psql -c 'create database cs50_sql_tests;' -U postgres
  - pip install mysqlclient psycopg2

install: make install

script: python test/sqltests.py
